# Generated by Django 5.1.4 on 2024-12-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS_Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('creator', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
